language: node_js

services:
  - mongodb

node_js:
  - 14.15.1

env:
  - NODE_ENV=test

install:
  - npm install

before_script:
  - sleep 15
  - mongo mydb_test --eval 'db.createUser({user:"travis",pwd:"test",roles:["readWrite"]});'

script:
  - npm test

after_success: npm run coverage